### ISSUE TITLE
getAll for non-unique index

### ISSUE THREAD

**Issue by retorquere** [qualified-cactus/promised-db#2]
I want to delete all occurrences of a non-unique property index. How do I do this with this library?

**Comment by qualified-cactus** [comment]
Since [IDBIndex](https://developer.mozilla.org/en-US/docs/Web/API/IDBIndex) has no delete method, you probably want to iterate over the index and delete each object one by one.

Example: 

```typescript
nameIndex.iterator.iterateValues(async (cursor)=>{
    console.log(cursor.key)  // access index key
    console.log(cursor.primaryKey) // access primary key
    console.log(cursor.value) // access object
    await cursor.delete() // or delete value using cursor
},{
    query: TodoTask.NameIndex.lowerBound("a"), // iterate over name starting with "a",
    direction: "prev" // descending order
})
```

**Comment by retorquere** [comment]
In my case, each object has the property `itemID`, and I want to delete all objects that have, say, `itemID = 4`. I would use `.only` for that then I suppose?

Is there a way to call this with a `for await` loop? I thought the iterator would allow doing things like that?

**Comment by qualified-cactus** [comment]
Sorry no, I did not implement iteration protocols. I might look into this in the future.

**Comment by retorquere** [comment]
But yes on the `.only`, right?

**Comment by retorquere** [comment]
How do you abandon an iteration midway if you've found what you need? Do you always have to iterate the full query?

**Comment by retorquere** [comment]
I suppose I could call `cursor.advance(<very high number>)`?

**Comment by qualified-cactus** [comment]
> How do you abandon an iteration midway if you've found what you need? Do you always have to iterate the full query?

You can use `CursorIterationOption.limit` to limit your result count. There is currently no break functionality.

**Comment by qualified-cactus** [comment]
> But yes on the `.only`, right?

Ya, you probably want to use `.only`
